version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      time: '06:00'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
      time: '06:00'
    groups:
      sentry:
        patterns:
          - '@sentry/*'
    open-pull-requests-limit: 10
