name = "github-bot"
account_id = "354031eb286d3580768d168016cfaabf"
workers_dev = true
compatibility_date = "2022-01-23"
main = "./src/index.ts"
node_compat = true

[version_metadata]
binding = "CF_VERSION_METADATA"
