name = "bot"
type = "javascript"
zone_id = "2e43be6db95acabf68db9c9d8c669a52"
account_id = "4ef0e0b43b821a981b4173298e18bf53"
route = "https://github-bot.hacs.xyz/*"
workers_dev = true
compatibility_date = "2022-01-23"

[build]
command = "yarn install && yarn build"
[build.upload]
format = "service-worker"
